apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-app-deployment 

spec:
  replicas: 3 
  selector:
    matchLabels:
      app: my-static-site
  template:
    metadata:
      labels:
        app: my-static-site
    spec:
      containers:
      - name: my-web
        image: haroonshahroom/my-static-site:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80