name: devops playground 

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Show secret value
        run: echo "${{ secrets.MY_NAME }}"

  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Create playground file
        run: echo "Hello, DevOps Playground!" > playground.txt
      - name: Upload playground artifact
        uses: actions/upload-artifact@v4
        with:
          name: playground
          path: playground.txt

  read-file:
    runs-on: ubuntu-latest
    needs: create-file
    steps:
      - name: Download playground artifact
        uses: actions/download-artifact@v4
        with:
          name: playground
      - name: Read playground file
        run: cat playground.txt

  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Show Node.js version
        run: node -v
        
  call-reusable-workflow:
    uses: ./.github/workflows/reuseable-workflow.yml            

