name: QA Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Shows files in the repository
        run: ls -la

      - name: Show current directory
        run: pwd

      - name: Branches 
        run: git branch  
      